# fly.toml app configuration file generated for gateways-api on 2023-06-18T17:18:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gateways-api"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
